GET http://localhost:8080/group/list
###
GET http://localhost:8080/function/list
###
GET http://localhost:8080/function/params
Content-Type: application/json

{
    "key":"#TERMINAL_COMMAND"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"comando mac para ver ruta en mi terminal, solo el valor y nada mas"
}