GET http://localhost:8080/group/list
###
GET http://localhost:8080/function/list
###
GET http://localhost:8080/function/params
Content-Type: application/json

{
    "key":"#TERMINAL_COMMAND"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero generar un archivo con elk nombre punto env para mis credenciales de a doble ese y segun tu consideracion si es mejor en ruta princial o en la carpeta bl"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"me gustaria insertar un comando vacio en la terminal"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"un entre vacio en la terminal po fa vo"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"soy jose y quiero un enter vacio en la terminal"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero abrir el archivo hola mundo punto yava"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero abrir la carpeta utils"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero generar un nuevo archivo llamado catalog para mis pruebas y debe estar dentro de la carpeta http"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero generar un nuevo archivo llamado catalog dentro de la carpeta de pruebas debe ser yava"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero generar un nuevo archivo llamado catalog dentro de la carpeta de pruebas"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero generar una nueva subcarpeta llamada utils dentro de bl."
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero que poingas en cursor en la linea numero 5 del archivo abierto"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero que selecciones la linea completa desde la 5 a la 10"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"quiero que elimines la linea numero "
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"debes de borrar la linea numero 20 y copntar un chiste"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"debes insertar codigo de una funcion para verificar si un numero es primo en python en la linea 5"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
  "message":"debes insertar codigo de una funcion en python en la fila 5"
}